# Generated by Django 5.2.16 on 2026-07-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0002_alter_inquiry_options_alter_inquiry_inquiry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='inquiry_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'General'), (1, 'Software Development'), (2, 'Cloud & DevOps'), (3, 'Cybersecurity'), (4, 'IT Consulting'), (5, 'Managed IT Support')], default=0),
        ),
    ]
