# Generated by Django 5.2.16 on 2026-07-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('icon', models.CharField(default='bi-gear-fill', help_text='Bootstrap icon class, e.g. "bi-cloud-fill".', max_length=60)),
                ('summary', models.CharField(help_text='Short one-line summary shown in cards.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Full description shown on the service detail page.')),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=True, help_text='Show this service on the home page.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers are shown first.')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
